--- 
en-wp: 
  url: http://en.wikipedia.org/w/api.php
  pw: password 
  user: username
commons: 
  url: http://commons.wikimedia.org/w/api.php
  pw: password 
  user: username 
en-wv: 
  url: http://en.wikivoyage.org/w/api.php
  pw: password
  user: username 
local:
  url: http://localhost/w/api.php
  pw: password 
  user: username
